name: NukkitKits
version: 2.0.0
main: me.tripulante.advancedkits.Main
api: ["1.0.0", "1.0.10", "1.0.13"]
author: Tripulante1404
softdepend: ["EconomyAPI"]

commands:
  kit:
    description: "Sistema avanzado de kits con UI"
    usage: "/kit [create|edit|delete]"
    aliases: ["kits"]

permissions:
  advancedkits.admin:
    description: "Permite crear y editar kits"
    default: op
